language: python
python:
  - "3.6"

before_install:
  - |
    cd $HOME
    git clone https://github.com/xbmc/addon-check
    cd $TRAVIS_BUILD_DIR

install:
  - pip install $HOME/addon-check/
  - pip install pylint

before_script:
  - |
    rm -f .gitattributes
    mv .pylintrc $HOME
    cd $HOME

script:
  - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=jarvis
  - pylint $TRAVIS_BUILD_DIR/resources/lib/
